//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{Recipient, True, UserId};

impl_payload! {
    /// Use this method to delete an ephemeral message. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#deleteephemeralmessage).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub DeleteEphemeralMessage (DeleteEphemeralMessageSetters) => True {
        required {
            /// Unique identifier for the target chat
            pub chat_id: Recipient [into],
            /// Unique identifier of the user who received the ephemeral message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message
            pub ephemeral_message_id: i64,
        }
    }
}
