//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, MessageEntity, ParseMode, Recipient, True, UserId};

impl_payload! {
    /// Use this method to edit caption of an ephemeral message. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#editephemeralmessagecaption).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditEphemeralMessageCaption (EditEphemeralMessageCaptionSetters) => True {
        required {
            /// Unique identifier for the target chat
            pub chat_id: Recipient [into],
            /// Unique identifier of the user who received the ephemeral message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message
            pub ephemeral_message_id: i64,
        }
        optional {
            /// New caption of the message, 0-1024 characters after entities parsing
            pub caption: String [into],
            /// Mode for parsing entities in the caption
            pub parse_mode: ParseMode,
            /// List of special entities that appear in the caption
            pub caption_entities: Vec<MessageEntity> [collect],
            /// Pass true if the caption must be shown above the message media
            pub show_caption_above_media: bool,
            /// An inline keyboard
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
