//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, InputMedia, Recipient, True, UserId};

impl_payload! {
    /// Use this method to edit animation, audio, document, photo, or video messages of an ephemeral message. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#editephemeralmessagemedia).
    #[derive(Debug, Clone, Serialize)]
    pub EditEphemeralMessageMedia (EditEphemeralMessageMediaSetters) => True {
        required {
            /// Unique identifier for the target chat
            pub chat_id: Recipient [into],
            /// Unique identifier of the user who received the ephemeral message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message
            pub ephemeral_message_id: i64,
            /// A JSON-serialized object for a new media content of the message
            pub media: InputMedia,
        }
        optional {
            /// An inline keyboard
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
