//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{OwnedGifts, UserId};

impl_payload! {
    /// Returns the gifts owned and hosted by a user. Returns OwnedGifts on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#getusergifts).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetUserGifts (GetUserGiftsSetters) => OwnedGifts {
        required {
            /// Unique identifier of the user
            pub user_id: UserId,
        }
        optional {
            /// Pass true to exclude unlimited gifts
            pub exclude_unlimited: bool,
            /// Pass true to exclude limited upgradable gifts
            pub exclude_limited_upgradable: bool,
            /// Pass true to exclude limited non-upgradable gifts
            pub exclude_limited_non_upgradable: bool,
            /// Pass true to exclude blockchain gifts
            pub exclude_from_blockchain: bool,
            /// Pass true to exclude unique gifts
            pub exclude_unique: bool,
            /// Pass true to sort by gift price
            pub sort_by_price: bool,
            /// Offset of the first entry to return
            pub offset: String [into],
            /// Maximum number of gifts to return; 1-100
            pub limit: u8,
        }
    }
}
