//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{KeyboardButton, PreparedKeyboardButton, UserId};

impl_payload! {
    /// Stores a keyboard button that can be used by a user within a Mini App. Returns a PreparedKeyboardButton object.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#savepreparedkeyboardbutton).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SavePreparedKeyboardButton (SavePreparedKeyboardButtonSetters) => PreparedKeyboardButton {
        required {
            /// Unique identifier of the target user that can use the button
            pub user_id: UserId,
            /// A JSON-serialized object describing the button to be saved
            pub button: KeyboardButton,
        }
    }
}
