//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{
    BusinessConnectionId, CallbackQueryId, EffectId, InputFile, Message, MessageEntity, ParseMode,
    Recipient, ReplyMarkup, ReplyParameters, SuggestedPostParameters, ThreadId, TopicId, UserId,
};

impl_payload! {
    @[multipart = live_photo, photo]
    /// Use this method to send live photos. On success, the sent Message is returned.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#sendlivephoto).
    #[derive(Debug, Clone, Serialize)]
    pub SendLivePhoto (SendLivePhotoSetters) => Message {
        required {
            /// Unique identifier for the target chat or username of the target channel
            pub chat_id: Recipient [into],
            /// Live photo to send (video component)
            pub live_photo: InputFile,
            /// Static photo corresponding to the live photo
            pub photo: InputFile,
        }
        optional {
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
            /// Identifier of the direct messages topic
            pub direct_messages_topic_id: TopicId,
            /// Photo caption, 0-1024 characters after entities parsing
            pub caption: String [into],
            /// Mode for parsing entities in the caption
            pub parse_mode: ParseMode,
            /// List of special entities that appear in the caption
            pub caption_entities: Vec<MessageEntity> [collect],
            /// Pass true if the caption must be shown above the message media
            pub show_caption_above_media: bool,
            /// Pass true if the video needs to be covered with a spoiler animation
            pub has_spoiler: bool,
            /// Sends the message silently
            pub disable_notification: bool,
            /// Protects the contents of the sent message
            pub protect_content: bool,
            /// Pass true to allow up to 1000 messages per second
            pub allow_paid_broadcast: bool,
            /// Unique identifier of the message effect
            pub message_effect_id: EffectId,
            /// Parameters of the suggested post
            pub suggested_post_parameters: SuggestedPostParameters,
            /// Description of the message to reply to
            pub reply_parameters: ReplyParameters,
            /// Additional interface options
            pub reply_markup: ReplyMarkup [into],
            /// For outgoing ephemeral messages, unique identifier of the receiver
            pub receiver_user_id: UserId,
            /// For outgoing ephemeral messages, identifier of the callback query
            pub callback_query_id: CallbackQueryId,
        }
    }
}
