//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to process a received chat join request query by showing a Mini App to the user. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#sendchatjoinrequestwebapp).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendChatJoinRequestWebApp (SendChatJoinRequestWebAppSetters) => True {
        required {
            /// Unique identifier of the join request query
            pub chat_join_request_query_id: String [into],
            /// An HTTPS URL of a Web App to be opened
            pub web_app_url: String [into],
        }
    }
}
