//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InputProfilePhoto, True};

impl_payload! {
    /// Changes the profile photo of the bot. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#setmyprofilephoto).
    #[derive(Debug, Clone, Serialize)]
    pub SetMyProfilePhoto (SetMyProfilePhotoSetters) => True {
        required {
            /// The new profile photo to set
            pub photo: InputProfilePhoto,
        }
    }
}
