//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{True, UserId};

impl_payload! {
    /// Use this method to change the access settings of a managed bot. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#setmanagedbotaccesssettings).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetManagedBotAccessSettings (SetManagedBotAccessSettingsSetters) => True {
        required {
            /// User identifier of the managed bot whose access settings will be changed
            pub user_id: UserId,
            /// Pass true if only selected users can access the bot. The bot's owner can always access it
            pub is_access_restricted: bool,
        }
        optional {
            /// List of up to 10 identifiers of users who will have access to the bot in addition to its owner
            pub added_user_ids: Vec<UserId> [collect],
        }
    }
}
