//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{GuestQueryId, InlineQueryResult, SentGuestMessage};

impl_payload! {
    /// Use this method to reply to a received guest message. On success, a SentGuestMessage object is returned.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#answerguestquery).
    #[derive(Debug, PartialEq, Clone, Serialize)]
    pub AnswerGuestQuery (AnswerGuestQuerySetters) => SentGuestMessage {
        required {
            /// Unique identifier for the query to be answered
            pub guest_query_id: GuestQueryId,
            /// A JSON-serialized object describing the message to be sent
            pub result: InlineQueryResult,
        }
    }
}
