//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to process a received chat join request query. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#answerchatjoinrequestquery).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub AnswerChatJoinRequestQuery (AnswerChatJoinRequestQuerySetters) => True {
        required {
            /// Unique identifier of the join request query
            pub chat_join_request_query_id: String [into],
            /// Result of the query: `approve`, `decline`, or `queue`
            pub result: String [into],
        }
    }
}
