//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, Recipient, True, UserId};

impl_payload! {
    /// Use this method to edit only the reply markup of an ephemeral message. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#editephemeralmessagereplymarkup).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditEphemeralMessageReplyMarkup (EditEphemeralMessageReplyMarkupSetters) => True {
        required {
            /// Unique identifier for the target chat
            pub chat_id: Recipient [into],
            /// Unique identifier of the user who received the ephemeral message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message
            pub ephemeral_message_id: i64,
        }
        optional {
            /// An inline keyboard
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
