//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, LinkPreviewOptions, MessageEntity, ParseMode, Recipient, True, UserId};

impl_payload! {
    /// Use this method to edit text of an ephemeral message. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#editephemeralmessagetext).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditEphemeralMessageText (EditEphemeralMessageTextSetters) => True {
        required {
            /// Unique identifier for the target chat
            pub chat_id: Recipient [into],
            /// Unique identifier of the user who received the ephemeral message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message
            pub ephemeral_message_id: i64,
            /// New text of the message, 1-4096 characters after entities parsing
            pub text: String [into],
        }
        optional {
            /// Mode for parsing entities in the message text
            pub parse_mode: ParseMode,
            /// List of special entities that appear in message text
            pub entities: Vec<MessageEntity> [collect],
            /// Link preview generation options
            pub link_preview_options: LinkPreviewOptions,
            /// An inline keyboard
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
