//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BotAccessSettings, UserId};

impl_payload! {
    /// Use this method to get the access settings of a managed bot. Returns BotAccessSettings on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#getmanagedbotaccesssettings).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetManagedBotAccessSettings (GetManagedBotAccessSettingsSetters) => BotAccessSettings {
        required {
            /// Unique identifier of the managed bot
            pub user_id: UserId,
        }
    }
}
