//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{UserId, UserProfileAudios};

impl_payload! {
    /// Returns the list of profile audios of a user. Returns UserProfileAudios on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#getuserprofileaudios).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetUserProfileAudios (GetUserProfileAudiosSetters) => UserProfileAudios {
        required {
            /// Unique identifier of the target user
            pub user_id: UserId,
        }
        optional {
            /// Sequential number of the first audio to be returned
            pub offset: u32,
            /// Limits the number of audios to be retrieved. Values between 1-100 are accepted
            pub limit: u8,
        }
    }
}
