//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{UserId};

impl_payload! {
    /// Returns the token of a managed bot. Returns the token as a String on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#getmanagedbottoken).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetManagedBotToken (GetManagedBotTokenSetters) => String {
        required {
            /// Unique identifier of the managed bot
            pub user_id: UserId,
        }
    }
}
