//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{OwnedGifts, Recipient};

impl_payload! {
    /// Returns the gifts owned by a chat. Returns OwnedGifts on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#getchatgifts).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetChatGifts (GetChatGiftsSetters) => OwnedGifts {
        required {
            /// Unique identifier for the target chat or username of the target channel
            pub chat_id: Recipient [into],
        }
        optional {
            /// Pass true to exclude unsaved gifts
            pub exclude_unsaved: bool,
            /// Pass true to exclude saved gifts
            pub exclude_saved: bool,
            /// Pass true to exclude unlimited gifts
            pub exclude_unlimited: bool,
            /// Pass true to exclude limited upgradable gifts
            pub exclude_limited_upgradable: bool,
            /// Pass true to exclude limited non-upgradable gifts
            pub exclude_limited_non_upgradable: bool,
            /// Pass true to exclude blockchain gifts
            pub exclude_from_blockchain: bool,
            /// Pass true to exclude unique gifts
            pub exclude_unique: bool,
            /// Pass true to sort by gift price
            pub sort_by_price: bool,
            /// Offset of the first entry to return
            pub offset: String [into],
            /// Maximum number of gifts to return; 1-100
            pub limit: u8,
        }
    }
}
