//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{True};

impl_payload! {
    /// Removes the profile photo of the bot. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#removemyprofilephoto).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub RemoveMyProfilePhoto (RemoveMyProfilePhotoSetters) => True {
        required {}
    }
}
