//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{UserId};

impl_payload! {
    /// Replaces the token of a managed bot and returns the new token as a String on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#replacemanagedbottoken).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub ReplaceManagedBotToken (ReplaceManagedBotTokenSetters) => String {
        required {
            /// Unique identifier of the managed bot
            pub user_id: UserId,
        }
    }
}
