//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnectionId, EffectId, InputRichMessage, Message, Recipient, ReplyMarkup, ReplyParameters, SuggestedPostParameters, ThreadId, TopicId};

impl_payload! {
    /// Use this method to send rich messages. On success, the sent Message is returned.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#sendrichmessage).
    #[derive(Debug, Clone, Serialize)]
    pub SendRichMessage (SendRichMessageSetters) => Message {
        required {
            /// Unique identifier for the target chat or username of the target bot, supergroup or channel
            pub chat_id: Recipient [into],
            /// The message to be sent
            pub rich_message: InputRichMessage,
        }
        optional {
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
            /// Identifier of the direct messages topic
            pub direct_messages_topic_id: TopicId,
            /// Sends the message silently
            pub disable_notification: bool,
            /// Protects the contents of the sent message
            pub protect_content: bool,
            /// Pass true to allow up to 1000 messages per second
            pub allow_paid_broadcast: bool,
            /// Unique identifier of the message effect
            pub message_effect_id: EffectId,
            /// Parameters of the suggested post
            pub suggested_post_parameters: SuggestedPostParameters,
            /// Description of the message to reply to
            pub reply_parameters: ReplyParameters,
            /// Additional interface options
            pub reply_markup: ReplyMarkup [into],
        }
    }
}
