//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, MessageEntity, ParseMode, ThreadId, True};

impl_payload! {
    /// Use this method to stream a partial message to a user while the message is being generated. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#sendmessagedraft).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendMessageDraft (SendMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target private chat
            pub chat_id: ChatId [into],
            /// Unique identifier of the message draft; must be non-zero
            pub draft_id: i64,
        }
        optional {
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
            /// Text of the message to be sent, 0-4096 characters after entities parsing
            pub text: String [into],
            /// Mode for parsing entities in the message text
            pub parse_mode: ParseMode,
            /// List of special entities that appear in message text
            pub entities: Vec<MessageEntity> [collect],
        }
    }
}
