//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, InputRichMessage, ThreadId, True};

impl_payload! {
    /// Use this method to stream a partial rich message draft while the message is being generated. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#sendrichmessagedraft).
    #[derive(Debug, Clone, Serialize)]
    pub SendRichMessageDraft (SendRichMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target private chat
            pub chat_id: ChatId [into],
            /// Unique identifier of the message draft; must be non-zero
            pub draft_id: i64,
        }
        optional {
            /// Partial rich message content
            pub rich_message: InputRichMessage,
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
        }
    }
}
