//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{Recipient, True, UserId};

impl_payload! {
    /// Use this method to set a custom tag for a chat member. Returns True on success.
    ///
    /// [The official docs](https://core.telegram.org/bots/api#setchatmembertag).
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetChatMemberTag (SetChatMemberTagSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup
            pub chat_id: Recipient [into],
            /// Unique identifier of the target user
            pub user_id: UserId,
        }
        optional {
            /// New tag for the user; 0-16 characters. Pass an empty string to remove the tag
            pub tag: String [into],
        }
    }
}
